trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build src/NewRelic.Telemetry.Sdk.sln --configuration $(buildConfiguration)
  displayName: 'Build (configuration=$(buildConfiguration)'

- script: dotnet test src/**/*.Tests --no-build --no-restore --configuration $(buildConfiguration) --logger trx
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: CopyFiles@2
  inputs:
    contents: 'src/NewRelic.Telemetry.Sdk/bin/$(buildConfiguration)/**/*'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
