trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build src/NewRelic.Telemetry.Sdk.sln --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet test src/NewRelic.Telemetry.Sdk.Tests/NewRelic.Telemetry.Sdk.Tests.csproj --logger trx
  displayName: 'Run some tests'
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'