trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build src/NewRelic.Telemetry.sln --configuration $(buildConfiguration)
  displayName: 'Build (configuration=$(buildConfiguration))'

- script: dotnet test src/NewRelic.Telemetry.Tests --no-build --no-restore --configuration $(buildConfiguration) --logger trx
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: CopyFiles@2
  inputs:
    contents: 'src/NewRelic.Telemetry/bin/$(buildConfiguration)/**/*'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1

- task: NuGetCommand@2
  condition: and(succeeded(), eq(variables['pushNupkg'], 'true'))
  displayName: 'Push NuGet Packages'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet'