trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0
  inputs:
    versionSpec: '>=4.3.0' 

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'src/NewRelic.Telemetry.sln' 

- task: SonarCloudPrepare@1
#   condition: and ( succeeded(), eq(variables['Build.Reason'], 'PullRequest'), eq(variables['System.PullRequest.TargetBranch'], 'master'))
  displayName: 'Prepare SonarCloud analysis'
  inputs:
    SonarCloud: 'SonarCloud'
    organization: '$(SonarCloudOrganization)'
    projectKey: '$(SonarCloudProjectKey)'
    projectName: '$(SonarCloudProjectName)'
    projectVersion: '$(Build.BuildNumber)'
    extraProperties: |
     sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/TestResults/Coverage/coverage.opencover.xml
     sonar.exclusions=**/wwwroot/lib/**/*


- task: MSBuild@1
  displayName: 'Build (configuration=$(buildConfiguration))'
  inputs:
    solution: 'src/NewRelic.Telemetry.sln'
    configuration: $(buildConfiguration) 

- script: dotnet test src/NewRelic.Telemetry.Tests --no-build --no-restore --configuration $(buildConfiguration) --logger trx
  displayName: 'Run tests - TelemetrySDK'

- script: dotnet test src/OpenTelemetry.Exporter.NewRelic.Tests --no-build --no-restore --configuration $(buildConfiguration) --logger trx
  displayName: 'Run tests - OpenTelemetry'

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'


- task: CopyFiles@2
  inputs:
    contents: 'src/NewRelic.Telemetry/bin/$(buildConfiguration)/**/*'
    targetFolder: '$(Build.ArtifactStagingDirectory)/TelemetrySDK'

- task: CopyFiles@2
  inputs:
    contents: 'src/OpenTelemetry.Exporter.NewRelic/bin/$(buildConfiguration)/**/*'
    targetFolder: '$(Build.ArtifactStagingDirectory)/OpenTelemetry'

- task: SonarCloudAnalyze@1
#   condition: and ( succeeded(), eq(variables['Build.Reason'], 'PullRequest'), eq(variables['System.PullRequest.TargetBranch'], 'master'))
  displayName: 'Run SonarCloud code analysis'

- task: SonarCloudPublish@1
#   condition: and ( succeeded(), eq(variables['Build.Reason'], 'PullRequest'), eq(variables['System.PullRequest.TargetBranch'], 'master'))
  displayName: 'Publish SonarCloud quality gate results'
  




# Validate that the Sonicloud quality gate passed.
- task: PowerShell@2
  env:
      AuthKey : $(SonarCloudAuthKey)
      ProjKey : $(SonarCloudProjectKey)
  inputs:
    targetType: 'inline'
    script: |
      $token = [System.Text.Encoding]::UTF8.GetBytes($env:AuthKey + ":")
      $base64 = [System.Convert]::ToBase64String($token)
       
      $basicAuth = [string]::Format("Basic {0}", $base64)
      $headers = @{ Authorization = $basicAuth }
       
      $result = Invoke-RestMethod -Method Get -Uri http://sonarcloud.io/api/qualitygates/project_status?projectKey=$env:ProjKey -Headers $headers
      $result | ConvertTo-Json | Write-Host
       
      if ($result.projectStatus.status -eq "OK") {
      Write-Host "Quality Gate Succeeded"
      }else{
      throw "Quality gate failed"
      }





- task: PublishBuildArtifacts@1

- task: NuGetCommand@2
  condition: and(succeeded(), eq(variables['pushNupkgTelemetrySDK'], 'true'))
  displayName: 'Push NuGet Packages - Telemetry SDK'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/TelemetrySDK/**/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet'

- task: NuGetCommand@2
  condition: and(succeeded(), eq(variables['pushNupkgOpenTelemetry'], 'true'))
  displayName: 'Push NuGet Packages - OpenTelemetry Exporter'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/OpenTelemetry/**/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet'
