trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build src/NewRelic.Telemetry.Sdk.sln --configuration $(buildConfiguration)
  displayName: 'Build (configuration=$(buildConfiguration)'

- script: dotnet test src/**/*.Tests --no-build --no-restore --configuration $(buildConfiguration) --logger trx
  displayName: 'Run tests'
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'